import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import VNavbar from "@/components/Navbars/VNavbar";
import Sidebar2 from "@/components/Sidebar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <div className="flex flex-col w-full min-h-screen bg-bg text-text">
      <div className="w-full">
        <VNavbar />
      </div>
      <div className="flex w-full">
        <div className="relative flex-1">
          <Sidebar />
        </div>
        <div className="min-h-screen flex-4 bg-bgSoft">{children}</div>
      </div>
    </div>
  );
};

export default layout;
