import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import VNavbar from "@/components/Navbars/VNavbar";
import Sidebar2 from "@/components/Sidebar2";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <div className="w-full bg-bg">
      {/* mobile view */}
      <div className="md:hidden">
        <div className="w-full h-20 border-b bg-bg">
          <VNavbar />
        </div>

        <div className="w-full my-2 bg-bg">
          <Sidebar2 />
        </div>
        <div className="w-full min-h-screen pt-4 pl-4 bg-bgSoft">
          {children}
        </div>
        <div className="w-full h-20">
          <Footer />
        </div>
      </div>
      {/* desktop view */}
      <div className="flex-col hidden md:flex">
        <div className="w-full h-20 bg-bg">
          <VNavbar />
        </div>
        <div className="flex w-full">
          <div className="flex-1 w-full bg-bg">
            <Sidebar />
          </div>
          <div className="w-full min-h-screen pt-10 pl-10 mr-10 flex-4 bg-bgSoft">
            {children}
          </div>
        </div>
        <div className="w-full h-20 bg-bg">
          <Footer />
        </div>
      </div>
    </div>
  );
};

export default layout;
