import { Inter } from "next/font/google";
import "../globals.css";
import UNavbar from "@/components/Navbars/UNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-text ${inter.className}`}>
        <UNavbar />
        {children}
        Footer
      </body>
    </html>
  );
}
