import { NextProvider } from "../providers/NextProvider";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <NextProvider>
        <body className={`text-text ${inter.className}`}>{children}</body>
      </NextProvider>
    </html>
  );
}
